[project]
name = 'demo-subnet-nft-marketplace'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'

[[project.requirements]]
contract_id = 'SP2PABAF9FTAJYNFZH93XENAJ8FVY99RRM50D2JG9.nft-trait'
[contracts.subnet-demo-marketplace]
path = 'contracts/subnet-demo-marketplace.clar'
clarity_version = 2
epoch = 2.1

[contracts.parfait-nft]
path = 'contracts/parfait-nft-l2.clar'
clarity_version = 2
epoch = 2.1

[contracts.subnet]
path = 'contracts/subnet.clar'
clarity_version = 2
epoch = 2.1
[repl.analysis]
passes = []

[repl.analysis.check_checker]
strict = false
trusted_sender = true
trusted_caller = false
callee_filter = false
