[project]
name = 'demo-subnet-nft'
description = 'l1 contracts for subnet demo app'
authors = []
telemetry = false
cache_dir = '.cache'

[[project.requirements]]
contract_id = 'ST1NXBK3K5YYMD6FD41MVNP3JS1GABZ8TRVX023PT.nft-trait'

[[project.requirements]]
contract_id = 'ST13F481SBR0R7Z6NMMH8YV2FJJYXA5JPA0AD3HP9.subnet-traits-v1'

[contracts.parfait-nft]
path = 'contracts/parfait-nft.clar'
clarity_version = 2
epoch = 2.1

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = true
trusted_caller = false
callee_filter = false
